import React, { useState, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  Platform,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";
import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";

// ─── Theme (mirrors ScannerScreen) ────────────────────────────────────────────
const C = {
  bg:          "#0f0f0f",
  surface:     "#242424",
  elevated:    "#3a3a3a",
  border:      "#4a4a4a",
  muted:       "#6f6f6f",
  subtle:      "#8b8b8b",
  body:        "#cbcbcb",
  strong:      "#e2e2e2",
  heading:     "#eeeeee",
  accent:      "#6366f1",
  accentDim:   "rgba(99,102,241,0.15)",
  accentBorder:"rgba(99,102,241,0.35)",
  success:     "#4ade80",
  successDim:  "rgba(74,222,128,0.12)",
  error:       "#f87171",
  errorDim:    "rgba(248,113,113,0.12)",
  errorBorder: "rgba(248,113,113,0.3)",
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
function detectType(raw) {
  if (/^https?:\/\//i.test(raw)) return "URL";
  if (/^mailto:/i.test(raw)) return "Email";
  if (/^tel:/i.test(raw)) return "Phone";
  if (/^(BEGIN:VCARD|BEGIN:VCAL)/i.test(raw)) return "Contact / Calendar";
  if (/^WIFI:/i.test(raw)) return "Wi-Fi";
  return "Text";
}

function formatDate(iso) {
  return new Date(iso).toLocaleString(undefined, {
    year: "numeric", month: "short", day: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
  });
}

// ─── PDF HTML template ────────────────────────────────────────────────────────
function buildHtml({ raw, type, scannedAt }) {
  const escaped = raw
    .replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const isUrl = type === "URL";
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>QR Scan Report</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
       background:#f8fafc;color:#1e293b;padding:40px 48px}
  .header{display:flex;align-items:center;gap:16px;padding-bottom:24px;
          border-bottom:2px solid #e2e8f0;margin-bottom:32px}
  .logo{width:48px;height:48px;background:#6366f1;border-radius:12px;
        display:flex;align-items:center;justify-content:center;
        font-size:18px;font-weight:800;color:#fff;flex-shrink:0;
        line-height:48px;text-align:center}
  .header-text h1{font-size:22px;font-weight:800;color:#0f172a}
  .header-text p{font-size:13px;color:#64748b;margin-top:3px}
  .badge{display:inline-block;background:#ede9fe;color:#5b21b6;
         font-size:12px;font-weight:700;letter-spacing:.5px;
         padding:4px 12px;border-radius:20px;margin-bottom:20px;text-transform:uppercase}
  .card{background:#fff;border-radius:12px;border:1px solid #e2e8f0;
        padding:24px 28px;margin-bottom:20px}
  .card-title{font-size:11px;font-weight:700;letter-spacing:1px;
              text-transform:uppercase;color:#94a3b8;margin-bottom:10px}
  .card-value{font-size:15px;color:#0f172a;word-break:break-all;line-height:1.6}
  .card-value.mono{font-family:'Courier New',Courier,monospace;background:#f1f5f9;
                   padding:12px 14px;border-radius:8px;font-size:13px}
  .url-link{color:#6366f1;text-decoration:underline}
  .meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  .footer{margin-top:40px;padding-top:20px;border-top:1px solid #e2e8f0;
          text-align:center;font-size:12px;color:#94a3b8}
</style>
</head>
<body>
<div class="header">
  <div class="logo">QR</div>
  <div class="header-text">
    <h1>QR Scan Report</h1>
    <p>Generated by QR PDF Scanner</p>
  </div>
</div>
<div class="badge">${type}</div>
<div class="card">
  <div class="card-title">Scanned Content</div>
  <div class="card-value mono">${isUrl ? `<a class="url-link" href="${escaped}">${escaped}</a>` : escaped}</div>
</div>
<div class="meta-grid">
  <div class="card">
    <div class="card-title">Content Type</div>
    <div class="card-value">${type}</div>
  </div>
  <div class="card">
    <div class="card-title">Scanned At</div>
    <div class="card-value">${formatDate(scannedAt)}</div>
  </div>
</div>
<div class="card">
  <div class="card-title">Character Count</div>
  <div class="card-value">${raw.length} characters</div>
</div>
<div class="footer">
  QR PDF Scanner &nbsp;•&nbsp; Report generated ${formatDate(new Date().toISOString())}
</div>
</body>
</html>`;
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function ResultScreen({ data, onReset }) {
  const { raw, type: barcodeType, scannedAt } = data;
  const contentType = detectType(raw);
  const [status, setStatus] = useState("idle");
  const [pdfUri, setPdfUri] = useState(null);

  const generateAndSharePdf = useCallback(async () => {
    setStatus("generating");
    try {
      let Print;
      try { Print = await import("expo-print"); }
      catch { throw new Error("expo-print is not installed. Run: npx expo install expo-print"); }

      const html = buildHtml({ raw, type: contentType, scannedAt });
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const dest = FileSystem.cacheDirectory + `QR_Scan_${Date.now()}.pdf`;
      await FileSystem.moveAsync({ from: uri, to: dest });
      setPdfUri(dest);
      setStatus("done");
    } catch (err) {
      console.error(err);
      setStatus("error");
      Alert.alert("PDF Error", err.message || "Could not generate PDF.");
    }
  }, [raw, contentType, scannedAt]);

  const sharePdf = useCallback(async () => {
    if (!pdfUri) return;
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      Alert.alert("Sharing unavailable", "Your device does not support file sharing.");
      return;
    }
    await Sharing.shareAsync(pdfUri, {
      mimeType: "application/pdf",
      dialogTitle: "Share QR Scan Report",
    });
  }, [pdfUri]);

  return (
    <SafeAreaView style={s.safe} edges={["top", "bottom"]}>
      <ScrollView contentContainerStyle={s.scroll} bounces={false}>

        {/* Top bar */}
        <View style={s.topBar}>
          <TouchableOpacity onPress={onReset} style={s.backBtn} activeOpacity={0.8}>
            <Ionicons name="arrow-back" size={18} color={C.accent} />
            <Text style={s.backText}>Scan Again</Text>
          </TouchableOpacity>
        </View>

        {/* Success badge */}
        <View style={s.successBadge}>
          <Ionicons name="checkmark-circle" size={44} color={C.success} style={{ marginBottom: 12 }} />
          <Text style={s.successTitle}>QR Code Scanned!</Text>
          <Text style={s.successSub}>Review the data below, then generate your PDF.</Text>
        </View>

        {/* Data cards */}
        <View style={s.card}>
          <Text style={s.cardLabel}>CONTENT TYPE</Text>
          <View style={s.typePill}>
            <Text style={s.typePillText}>{contentType}</Text>
          </View>
        </View>

        <View style={s.card}>
          <Text style={s.cardLabel}>SCANNED CONTENT</Text>
          <Text style={s.cardValue} selectable>{raw}</Text>
        </View>

        <View style={s.card}>
          <Text style={s.cardLabel}>SCANNED AT</Text>
          <Text style={s.cardValue}>{formatDate(scannedAt)}</Text>
        </View>

        <View style={s.card}>
          <Text style={s.cardLabel}>LENGTH</Text>
          <Text style={s.cardValue}>{raw.length} characters</Text>
        </View>

        {/* Actions */}
        <View style={s.actions}>
          {status === "idle" && (
            <TouchableOpacity style={s.primaryBtn} onPress={generateAndSharePdf} activeOpacity={0.85}>
              {/* <Ionicons name="document-text-outline" size={18} color="#fff" /> */}
              <Text style={s.primaryBtnText}>Generate PDF</Text>
            </TouchableOpacity>
          )}

          {status === "generating" && (
            <View style={s.loadingBox}>
              <ActivityIndicator color={C.accent} size="large" />
              <Text style={s.loadingText}>Building your PDF…</Text>
            </View>
          )}

          {status === "done" && (
            <>
              <View style={s.doneBox}>
                <MaterialCommunityIcons name="check-decagram" size={22} color={C.success} />
                <Text style={s.doneText}>PDF Ready!</Text>
              </View>
              <TouchableOpacity style={s.primaryBtn} onPress={sharePdf} activeOpacity={0.85}>
                <Ionicons name="share-outline" size={18} color="#fff" />
                <Text style={s.primaryBtnText}>Share PDF</Text>
              </TouchableOpacity>
              <TouchableOpacity style={s.secondaryBtn} onPress={generateAndSharePdf} activeOpacity={0.8}>
                <Ionicons name="refresh-outline" size={16} color={C.subtle} />
                <Text style={s.secondaryBtnText}>Regenerate</Text>
              </TouchableOpacity>
            </>
          )}

          {status === "error" && (
            <>
              <View style={s.errorBox}>
                <Ionicons name="warning-outline" size={16} color={C.error} />
                <Text style={s.errorText}>Failed to generate PDF</Text>
              </View>
              <TouchableOpacity style={s.primaryBtn} onPress={generateAndSharePdf} activeOpacity={0.85}>
                <Text style={s.primaryBtnText}>Try Again</Text>
              </TouchableOpacity>
            </>
          )}

          <TouchableOpacity style={s.secondaryBtn} onPress={onReset} activeOpacity={0.8}>
            <Ionicons name="camera-outline" size={16} color={C.subtle} />
            <Text style={s.secondaryBtnText}>Scan Another QR</Text>
          </TouchableOpacity>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  scroll: { padding: 20, paddingBottom: 52 },

  topBar: { marginBottom: 20 },
  backBtn: { flexDirection: "row", alignItems: "center", gap: 6, alignSelf: "flex-start" },
  backText: { color: C.accent, fontSize: 14, fontWeight: "600" },

  successBadge: {
    alignItems: "center",
    backgroundColor: C.successDim,
    borderRadius: 16, padding: 24, marginBottom: 20,
    borderWidth: 1, borderColor: "rgba(74,222,128,0.2)",
  },
  successTitle: { color: C.heading, fontSize: 19, fontWeight: "800", marginBottom: 6 },
  successSub: { color: C.subtle, fontSize: 13, textAlign: "center", lineHeight: 19 },

  card: {
    backgroundColor: C.surface, borderRadius: 12, padding: 16,
    marginBottom: 12, borderWidth: 1, borderColor: C.border,
  },
  cardLabel: {
    color: C.muted, fontSize: 10, fontWeight: "700",
    letterSpacing: 1.2, marginBottom: 8,
  },
  cardValue: {
    color: C.body, fontSize: 14, lineHeight: 21,
    fontFamily: Platform.OS === "ios" ? "Courier New" : "monospace",
  },
  typePill: {
    alignSelf: "flex-start", backgroundColor: C.accentDim,
    paddingHorizontal: 14, paddingVertical: 5, borderRadius: 20,
    borderWidth: 1, borderColor: C.accentBorder,
  },
  typePillText: { color: "#a5b4fc", fontSize: 13, fontWeight: "700" },

  actions: { marginTop: 8, gap: 12 },
  primaryBtn: {
    backgroundColor: C.accent, borderRadius: 12,
    paddingVertical: 15, alignItems: "center",
    flexDirection: "row", justifyContent: "center", gap: 8,
  },
  primaryBtnText: { color: "#fff", fontSize: 15, fontWeight: "700" },
  secondaryBtn: {
    backgroundColor: C.surface, borderRadius: 12,
    paddingVertical: 15, alignItems: "center",
    flexDirection: "row", justifyContent: "center", gap: 8,
    borderWidth: 1, borderColor: C.border,
  },
  secondaryBtnText: { color: C.subtle, fontSize: 14, fontWeight: "600" },

  loadingBox: { alignItems: "center", gap: 12, paddingVertical: 24 },
  loadingText: { color: C.subtle, fontSize: 14 },

  doneBox: {
    flexDirection: "row", alignItems: "center",
    justifyContent: "center", gap: 8, paddingVertical: 10,
  },
  doneText: { color: C.success, fontSize: 16, fontWeight: "700" },

  errorBox: {
    backgroundColor: C.errorDim, borderRadius: 10, padding: 14,
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    gap: 8, borderWidth: 1, borderColor: C.errorBorder,
  },
  errorText: { color: C.error, fontSize: 13, fontWeight: "600" },
});