import { Platform } from "react-native";
import * as Application from "expo-application";
import * as SecureStore from "expo-secure-store";
import nacl from "tweetnacl";
import naclUtil from "tweetnacl-util";

// Activation servers are tried in this order. Add your primary and backup
// HTTPS domains here; both must serve the same license database and signing
// key, otherwise a failover can give inconsistent activation results.
// Only contacted at activation time — every subsequent launch verifies the
// stored credential locally via isDeviceAuthorized(), with no network call.
const ACTIVATION_SERVER_URLS = [
  "http://http://43.230.44.198/:3100",
  "https://license.fairtechsystems.com",
];

// Public half of the Ed25519 keypair generated by the license server's
// scripts/generate-keypair.js. Not secret — safe to ship in the app.
// The server signs activation credentials with the matching private key,
// which never leaves the server.
const ACTIVATION_PUBLIC_KEY_B64 = "dnSqTXB7Xi+qCM69mO40O3F4NbsGxYDD4Gq8UNeygUo=";

// --- Legacy offline HMAC scheme -------------------------------------------
// Kept only so devices activated before the online scheme existed keep
// working with zero action needed from those clients. Never used for new
// activations — activateDevice() below always goes through the server.
const ACTIVATION_SECRET_B64_LEGACY = "84L8ocMNdYKiV3XPKxk6Ldz9Jw7rzmiCZKwIyIJ4s1c=";

const ACTIVATION_STORAGE_KEY = "device_activation_key";

// Crockford base32: uppercase alphanumeric, excludes I/L/O/U to avoid
// look-alike confusion when read/typed by hand.
const CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

const CREDENTIAL_ALGO = "ed25519-v1";

export async function getDeviceId() {
  if (Platform.OS === "android") {
    return Application.getAndroidId();
  }
  return await Application.getIosIdForVendorAsync();
}

function concatBytes(a, b) {
  const out = new Uint8Array(a.length + b.length);
  out.set(a, 0);
  out.set(b, a.length);
  return out;
}

// HMAC-SHA512 built on tweetnacl's SHA-512 (nacl.hash) — legacy-only, kept
// identical to the original implementation so old stored keys keep verifying.
function hmacSha512(keyBytes, messageBytes) {
  const blockSize = 128;
  let key = keyBytes;
  if (key.length > blockSize) key = nacl.hash(key);
  const paddedKey = new Uint8Array(blockSize);
  paddedKey.set(key);
  const ipad = new Uint8Array(blockSize);
  const opad = new Uint8Array(blockSize);
  for (let i = 0; i < blockSize; i++) {
    ipad[i] = paddedKey[i] ^ 0x36;
    opad[i] = paddedKey[i] ^ 0x5c;
  }
  const inner = nacl.hash(concatBytes(ipad, messageBytes));
  return nacl.hash(concatBytes(opad, inner));
}

function base32Encode(bytes) {
  let bits = 0;
  let value = 0;
  let output = "";
  for (let i = 0; i < bytes.length; i++) {
    value = (value << 8) | bytes[i];
    bits += 8;
    while (bits >= 5) {
      output += CROCKFORD_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) {
    output += CROCKFORD_ALPHABET[(value << (5 - bits)) & 31];
  }
  return output;
}

function expectedLegacyActivationKey(deviceId) {
  const secretBytes = naclUtil.decodeBase64(ACTIVATION_SECRET_B64_LEGACY);
  const messageBytes = naclUtil.decodeUTF8(deviceId);
  const mac = hmacSha512(secretBytes, messageBytes).slice(0, 16); // 128 bits
  return base32Encode(mac).slice(0, 25); // 25 symbols = 125 bits
}

function normalizeActivationKey(activationKeyInput) {
  return activationKeyInput.toUpperCase().replace(/[^0-9A-Z]/g, "");
}

function verifyLegacyActivationKey(deviceId, activationKeyInput) {
  try {
    return (
      normalizeActivationKey(activationKeyInput) ===
      expectedLegacyActivationKey(deviceId)
    );
  } catch {
    return false;
  }
}

// --- Online Ed25519 credential scheme --------------------------------------

// Must match the canonical message format in server/src/signing.js exactly.
function canonicalMessage(credential) {
  return `${credential.algo}|${credential.licenseCode}|${credential.deviceId}|${credential.issuedAt}`;
}

function verifyCredential(credential, deviceId) {
  try {
    if (
      !credential ||
      credential.algo !== CREDENTIAL_ALGO ||
      credential.deviceId !== deviceId
    ) {
      return false;
    }
    const message = naclUtil.decodeUTF8(canonicalMessage(credential));
    const signature = naclUtil.decodeBase64(credential.signature);
    const publicKey = naclUtil.decodeBase64(ACTIVATION_PUBLIC_KEY_B64);
    return nacl.sign.detached.verify(message, signature, publicKey);
  } catch {
    return false;
  }
}

export async function isDeviceAuthorized() {
  const id = await getDeviceId();
  if (!id) return false;
  const stored = await SecureStore.getItemAsync(ACTIVATION_STORAGE_KEY);
  if (!stored) return false;

  try {
    const credential = JSON.parse(stored);
    if (credential && typeof credential === "object" && credential.signature) {
      return verifyCredential(credential, id);
    }
  } catch {
    // Not JSON — fall through to the legacy bare-string format below.
  }

  return verifyLegacyActivationKey(id, stored);
}

// Calls the activation server once to bind this device to the given license
// code, and persists the returned signed credential so isDeviceAuthorized()
// keeps passing offline on future launches. Returns a reason on failure so
// the UI can show a specific message.
export async function activateDevice(licenseCodeInput) {
  const id = await getDeviceId();
  if (!id || !licenseCodeInput || !licenseCodeInput.trim()) {
    return { ok: false, reason: "invalid_license" };
  }

  let serverFailed = false;
  for (const serverUrl of ACTIVATION_SERVER_URLS) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);
    let response;

    try {
      response = await fetch(`${serverUrl.replace(/\/+$/, "")}/api/activate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ licenseCode: licenseCodeInput.trim(), deviceId: id }),
        signal: controller.signal,
      });
    } catch {
      continue;
    } finally {
      clearTimeout(timeout);
    }

    let body;
    try {
      body = await response.json();
    } catch {
      serverFailed = true;
      continue;
    }

    // Client-side errors are definitive for this license and device, so do
    // not hide them by trying another server. Server errors can use failover.
    if (!response.ok) {
      if (response.status >= 500) {
        serverFailed = true;
        continue;
      }
      const knownReasons = ["invalid_license", "license_revoked", "device_mismatch"];
      const reason = knownReasons.includes(body?.error) ? body.error : "server_error";
      return { ok: false, reason };
    }

    const credential = body?.credential;
    if (!verifyCredential(credential, id)) {
      serverFailed = true;
      continue;
    }

    await SecureStore.setItemAsync(ACTIVATION_STORAGE_KEY, JSON.stringify(credential));
    return { ok: true };
  }

  return { ok: false, reason: serverFailed ? "server_error" : "network_error" };
}
